### ISSUE TITLE
"'A' tag has unexpected format" when <A> text is empty

### ISSUE THREAD

**Issue by workproduct** [nzkeith/delicious-to-evernote#2]
so first, i removed the lock file because im guessing those are for blocking different versions from being executed? anyways so did that then ran it and got the following.

bundle exec ruby delicious_to_evernote.rb
delicious_to_evernote.rb:68:in `parse_a': 'A' tag has unexpected format: "<A HREF=\"http://wiki.ipisoft.com/Quick_Start_Guide_for_Multiple_PlayStation_Eye_Cameras_Configuration\" ADD_DATE=\"1362428192\" PRIVATE=\"0\" TAGS=\"motion capture,playstation eye,ipisoft\">" (RuntimeError)
	from delicious_to_evernote.rb:61:in `process_fragment'
	from delicious_to_evernote.rb:51:in `block in process_fragments'
	from delicious_to_evernote.rb:51:in `each'
	from delicious_to_evernote.rb:51:in `process_fragments'
	from delicious_to_evernote.rb:21:in `block (2 levels) in main'
	from /usr/lib/ruby/vendor_ruby/nokogiri/xml/builder.rb:391:in `insert'
	from /usr/lib/ruby/vendor_ruby/nokogiri/xml/builder.rb:375:in `method_missing'
	from delicious_to_evernote.rb:16:in `block in main'
	from /usr/lib/ruby/vendor_ruby/nokogiri/xml/builder.rb:293:in `initialize'
	from delicious_to_evernote.rb:14:in `new'
	from delicious_to_evernote.rb:14:in `main'
	from delicious_to_evernote.rb:98:in `<main>'

**Comment by nzkeith** [comment]
@workproduct I've made a change that should resolve this issue for you. Note that your scenario results in an empty note title, which Evernote doesn't permit, so I've defaulted the title in this case to '?'.

Also I've modified the script to skip links that it doesn't understand rather than stopping, which may help with this or any other incompatible links in your Delicious export file.
